### ISSUE TITLE
Listening . at 0.0.0.0:8888

### ISSUE THREAD

**Issue by shuneguchi** [tyoshizawa/httpmd#2]
My apology for this stupid question.

When I open my .md file using HTTPMD, it starts listening the local port of 8888. Do I need to access to local port using GUI browser to view this markdown?

``` shell
[root@ansible Ansible]# httpmd ansible-ntp/README.md
2016/06/17 17:32:03 Listening . at 0.0.0.0:8888
```

Please advise...

**Comment by shuneguchi** [comment]
My apology, again.

I was able to browse the page via my local browser accessing to localhost:8888.

``` shell
[root@ansible Ansible]# httpmd
```

**Comment by tyoshizawa** [comment]
Sorry about the poor documentation. I'll improve README.md soon.
